### ISSUE TITLE
Working with windows

### ISSUE THREAD

**Issue by IvanOstr** [sdickreuter/python-andor#1]
Hello,
Does this work with windows and andor iDus 401A camera and SR303i spectrometer?
Also, from your exprience, what are the best options for my setup (described above)? 
I find a couple of python libs and unsure what to choose.

Thank you,
Ivan

**Comment by sdickreuter** [comment]
Hi Ivan,

it should work fine with all cameras supported by the Andor SDK2 and all supported spectrometers. I use it with an iDus416 and also a SR303i. There is some functionality that I haven't implemented, but we use it in the lab every day.
I guess it won't run on windows without modification, as it uses cython to access the the SDK and I think on windows one has to do that in a bit a different way.
You could try using [https://github.com/hamidohadi/pyandor](https://github.com/hamidohadi/pyandor) (which uses ctypes instead of cython), that's what inspired me to write my own module because it didn't work out for me, but it might be the right one for you.

cheers
Simon

**Comment by sdickreuter** [comment]
I'm closing this, but if you have any further questions feel free to reopen this issue.
