### ISSUE TITLE
Change temperature of spectrometer

### ISSUE THREAD

**Issue by Spandan2003** [sdickreuter/python-andor#2]
Hi,

I am working on Andor spectrometer Kymera 328i. It requires the temperature to go to -80 degrees C. However in the spectrometer.py the temperature is set as -15. Then in the andorSDK.pyx the temperature to shutdown is -10. Should I change them? I am afraid that changing this might cause some error in the code.
Please help me.

Thankyou for writing such an amazing code. It is very helpful.
Spandan

**Comment by sdickreuter** [comment]
Hi Spandan,

thank you for your kind words, it's always nice to know that ones code is useful :)

Unfortunately I am no longer able to maintain the code because I left university so there might be some issues with the newest versions of the AndorSDK, but If you have the basic functions running it should be fine.

Now to your specific Problem:
The -15°C are just used as a starting point, changing this won't cause problems, but you can also use `spectrometer.SetTemperature(-80)` to set the detector temperature to -80°C.

The temperature shutdown is set to -10°C, because then it is safe to switch of the coolers and the detector can safely warm up to room temperature on its own.
The shutdown procedure sets the temperature to -10°C and waits until it is reached before shutting down the coolers.
Somewhere in the SDK manuals there is written that one should not turn off the detector driver before it is warmer than -20°C to prevent stresses from fast temperature changes.
So I would advise you to check if this is true for your detector also.

But this can only happen if for some reason your python program crashes and the spectrometer object is not finalized correctly. 
So for testing your code I would always use a higher temperature and only use the -80°C when you are sure that your code is stable.
To mitigate this issues, what I did is to run all the spectrometer stuff in a separate process:
[spectrometer_server.py](https://github.com/sdickreuter/SCNR2/blob/master/spectrometer_server.py)
This also helps with the AndorSDK not being threadsafe! (at least it wasn't three years ago)

There probably is a way to make the python code failsafe using python finalizers, but I don't have an idea how to do that.

Also if you haven't yet, please check the last part of the README, this will also help your program to be more safe.
If somehow your program crashes when the detector is below -20°C, you can still start the AndorSolis programm and use that to switch on the Cooler again and let it slowly warmup.

**Comment by Spandan2003** [comment]
Hi,
I have finally started working on the Andor code. However, I am getting the MissingImport error whenever I try to run the test.py file. 
![image](https://user-images.githubusercontent.com/99035174/228973256-8bee3d23-549d-482f-b0ba-4bde1e9fa2dc.png)
I attempted to install the module by running  `pip install .` and `python setup.py install`. However in both the cases I am getting an error
![image](https://user-images.githubusercontent.com/99035174/228973053-345dc4ca-52e8-4fac-aba2-0aa81dede3e8.png)

I hope that you will guide me into at least being able to import the modules. I am extremely grateful to this code as it has saved me multiple times.
Thanking You.

Spandan.
